#!/usr/bin/with-contenv sh
# Disable IPv6 (requires privileged mode).
# Nginx daemon listens on tcp6 socket. Because of this upstream may receive HTTP request from 0:0:0:0:0:0:0:1
# as well as from 127.0.0.1. This forces to mangle with application server ACLs which isn't always appropriate.
sysctl -w net.ipv6.conf.all.disable_ipv6=1
sysctl -w net.ipv6.conf.default.disable_ipv6=1
sysctl -w net.ipv6.conf.lo.disable_ipv6=1
